import LogConcavity
import Mathlib.RingTheory.MvPolynomial.Ideal

/-!
# The Koszul complex on the three coordinate variables

Mathlib v4.31 has no Koszul complex, so this file builds the one we need by
hand: the complex

```
0 → M → M³ → M³ → M → 0
      d₃    d₂    d₁
```

attached to the regular sequence `(x₀, x₁, x₂)` in `R3 k = k[x₀,x₁,x₂]` and a
module `M`.  Writing `e₀, e₁, e₂` for the exterior generators and indexing
`Λ²` by `u₀ = e₁∧e₂`, `u₁ = e₂∧e₀`, `u₂ = e₀∧e₁`, the differentials are the
usual ones; concretely `d₁` is the dot product with `(x₀,x₁,x₂)`, `d₂` is the
cross product with it, and `d₃` is multiplication by it.

The point of the complex is its two ends:

* `ker d₃` is the socle `(0 :_M m)` (`ker_d₃_eq`, `mem_ker_d₃_iff`);
* `M ⧸ range d₁` is `M ⧸ m M`.

and the point of the middle is exactness, proved here for `M = R3 k`
(`ker_d₁_eq_range_d₂`, `ker_d₂_eq_range_d₃`, `d₃_injective`) and transferred
to finite free modules (`free` section).  That makes the complex a free
resolution of `k` and lets Koszul homology of a free module vanish in
positive degrees, which is what an eventual computation of the last Betti
number needs.
-/

open scoped BigOperators

namespace LogConcavity

namespace Koszul

universe u v w

open MvPolynomial

section Differentials

variable (k : Type u) [Field k] (M : Type v) [AddCommGroup M] [Module (R3 k) M]

/-- `Λ³ ⊗ M → Λ² ⊗ M`: multiplication by the vector of variables. -/
noncomputable def d₃ : M →ₗ[R3 k] (Fin 3 → M) where
  toFun m := fun i => (X i : R3 k) • m
  map_add' m m' := by funext i; exact smul_add _ _ _
  map_smul' c m := by funext i; exact (smul_comm (X i : R3 k) c m)

/-- `Λ² ⊗ M → Λ¹ ⊗ M`: the cross product with the vector of variables. -/
noncomputable def d₂ : (Fin 3 → M) →ₗ[R3 k] (Fin 3 → M) where
  toFun g := fun i =>
    ((X (i + 2) : R3 k) • g (i + 1) : M) - ((X (i + 1) : R3 k) • g (i + 2) : M)
  map_add' g g' := by
    funext i
    simp only [Pi.add_apply, smul_add]
    abel
  map_smul' c g := by
    funext i
    simp only [Pi.smul_apply, RingHom.id_apply, smul_sub,
      smul_comm (X (i + 2) : R3 k) c, smul_comm (X (i + 1) : R3 k) c]

/-- `Λ¹ ⊗ M → Λ⁰ ⊗ M`: the dot product with the vector of variables. -/
noncomputable def d₁ : (Fin 3 → M) →ₗ[R3 k] M where
  toFun f := ∑ i : Fin 3, (X i : R3 k) • f i
  map_add' f f' := by simp [smul_add, Finset.sum_add_distrib]
  map_smul' c f := by simp [Finset.smul_sum, smul_comm c]

@[simp] lemma d₃_apply (m : M) (i : Fin 3) : d₃ k M m i = (X i : R3 k) • m := rfl

lemma d₂_apply (g : Fin 3 → M) (i : Fin 3) :
    d₂ k M g i = (X (i + 2) : R3 k) • g (i + 1) - (X (i + 1) : R3 k) • g (i + 2) :=
  rfl

lemma d₂_apply_zero (g : Fin 3 → M) :
    d₂ k M g 0 = (X 2 : R3 k) • g 1 - (X 1 : R3 k) • g 2 := by
  simpa using d₂_apply k M g 0

lemma d₂_apply_one (g : Fin 3 → M) :
    d₂ k M g 1 = (X 0 : R3 k) • g 2 - (X 2 : R3 k) • g 0 := by
  simpa using d₂_apply k M g 1

lemma d₂_apply_two (g : Fin 3 → M) :
    d₂ k M g 2 = (X 1 : R3 k) • g 0 - (X 0 : R3 k) • g 1 := by
  simpa using d₂_apply k M g 2

lemma d₁_apply (f : Fin 3 → M) :
    d₁ k M f = (X 0 : R3 k) • f 0 + (X 1 : R3 k) • f 1 + (X 2 : R3 k) • f 2 := by
  simp [d₁, Fin.sum_univ_three]

lemma d₁_comp_d₂ : (d₁ k M).comp (d₂ k M) = 0 := by
  apply LinearMap.ext
  intro g
  rw [LinearMap.comp_apply, d₁_apply, d₂_apply_zero, d₂_apply_one, d₂_apply_two]
  simp only [smul_sub, smul_smul, LinearMap.zero_apply]
  rw [mul_comm (X 0 : R3 k) (X 2), mul_comm (X 1 : R3 k) (X 2),
    mul_comm (X 1 : R3 k) (X 0)]
  abel

lemma d₂_comp_d₃ : (d₂ k M).comp (d₃ k M) = 0 := by
  apply LinearMap.ext
  intro m
  funext i
  rw [LinearMap.comp_apply, d₂_apply]
  simp only [d₃_apply, smul_smul, LinearMap.zero_apply, Pi.zero_apply]
  rw [mul_comm (X (i + 2) : R3 k)]
  exact sub_self _

variable {k M}

lemma range_d₂_le_ker_d₁ : LinearMap.range (d₂ k M) ≤ LinearMap.ker (d₁ k M) := by
  rintro _ ⟨g, rfl⟩
  have := congrArg (fun f => f g) (d₁_comp_d₂ k M)
  simpa [LinearMap.comp_apply] using this

lemma range_d₃_le_ker_d₂ : LinearMap.range (d₃ k M) ≤ LinearMap.ker (d₂ k M) := by
  rintro _ ⟨m, rfl⟩
  have := congrArg (fun f => f m) (d₂_comp_d₃ k M)
  simpa [LinearMap.comp_apply] using this

/-- The top of the Koszul complex sees exactly the socle. -/
lemma mem_ker_d₃_iff (m : M) :
    m ∈ LinearMap.ker (d₃ k M) ↔ ∀ i : Fin 3, (X i : R3 k) • m = 0 := by
  constructor
  · intro hm i
    have := congrArg (fun f => f i) (LinearMap.mem_ker.mp hm)
    simpa using this
  · intro hm
    apply LinearMap.mem_ker.mpr
    funext i
    simpa using hm i

end Differentials

/-! ## Exactness over the polynomial ring itself -/

section Ring

variable {k : Type u} [Field k]

/-- The core regularity fact: a variable outside `S` is a nonzerodivisor
modulo the ideal generated by the variables in `S`. -/
lemma mem_span_X_of_X_mul_mem (S : Set (Fin 3)) (j : Fin 3) (hj : j ∉ S)
    {f : R3 k} (h : (X j : R3 k) * f ∈ Ideal.span ((X (R := k)) '' S : Set (R3 k))) :
    f ∈ Ideal.span ((X (R := k)) '' S : Set (R3 k)) := by
  have hsupport := MvPolynomial.mem_ideal_span_X_image.mp h
  rw [MvPolynomial.mem_ideal_span_X_image]
  intro m hm
  have hm' : Finsupp.single j 1 + m ∈ ((X j : R3 k) * f).support := by
    rw [MvPolynomial.support_X_mul]
    exact Finset.mem_map.mpr ⟨m, hm, rfl⟩
  obtain ⟨i, hiS, hi⟩ := hsupport _ hm'
  refine ⟨i, hiS, ?_⟩
  have hij : i ≠ j := by
    rintro rfl
    exact hj hiS
  simpa [Finsupp.single_apply, hij] using hi

/-- Membership in the ideal of a single variable is divisibility. -/
lemma mem_span_X_singleton_iff {i : Fin 3} {f : R3 k} :
    f ∈ Ideal.span ((X (R := k)) '' ({i} : Set (Fin 3)) : Set (R3 k)) ↔
      (X i : R3 k) ∣ f := by
  rw [Set.image_singleton, Ideal.mem_span_singleton]

/-- Membership in the ideal of two variables, unpacked. -/
lemma mem_span_X_pair_iff {i j : Fin 3} {f : R3 k} :
    f ∈ Ideal.span ((X (R := k)) '' ({i, j} : Set (Fin 3)) : Set (R3 k)) ↔
      ∃ a b : R3 k, f = a * X i + b * X j := by
  rw [Set.image_insert_eq, Set.image_singleton, Ideal.mem_span_pair]
  constructor
  · rintro ⟨a, b, rfl⟩
    exact ⟨a, b, by ring⟩
  · rintro ⟨a, b, rfl⟩
    exact ⟨a, b, by ring⟩

lemma d₃_injective : Function.Injective (d₃ k (R3 k)) := by
  intro m m' h
  have h0 := congrArg (fun f => f 0) h
  simp only [d₃_apply, smul_eq_mul] at h0
  exact mul_left_cancel₀ (MvPolynomial.X_ne_zero 0) h0

lemma ker_d₂_eq_range_d₃ :
    LinearMap.ker (d₂ k (R3 k)) = LinearMap.range (d₃ k (R3 k)) := by
  refine le_antisymm ?_ range_d₃_le_ker_d₂
  intro g hg
  have hg' := LinearMap.mem_ker.mp hg
  have h2 : (X 1 : R3 k) * g 0 - (X 0 : R3 k) * g 1 = 0 := by
    have := congrArg (fun f => f 2) hg'
    simpa [d₂_apply_two, smul_eq_mul] using this
  have h1 : (X 0 : R3 k) * g 2 - (X 2 : R3 k) * g 0 = 0 := by
    have := congrArg (fun f => f 1) hg'
    simpa [d₂_apply_one, smul_eq_mul] using this
  -- `x₀` divides `g 0`, because `x₁ * g 0 = x₀ * g 1` lies in `(x₀)`.
  have hmem : (X 1 : R3 k) * g 0 ∈
      Ideal.span ((X (R := k)) '' ({0} : Set (Fin 3)) : Set (R3 k)) := by
    rw [mem_span_X_singleton_iff]
    exact ⟨g 1, by linear_combination h2⟩
  obtain ⟨h, hh⟩ :=
    mem_span_X_singleton_iff.mp (mem_span_X_of_X_mul_mem _ 1 (by simp) hmem)
  refine ⟨h, ?_⟩
  funext i
  fin_cases i
  · simpa [d₃_apply, smul_eq_mul] using hh.symm
  · -- `x₀ * g 1 = x₁ * g 0 = x₀ * (x₁ * h)`
    have : (X 0 : R3 k) * g 1 = (X 0 : R3 k) * ((X 1 : R3 k) * h) := by
      rw [hh] at h2; linear_combination -h2
    simpa [d₃_apply, smul_eq_mul] using
      (mul_left_cancel₀ (MvPolynomial.X_ne_zero 0) this).symm
  · have : (X 0 : R3 k) * g 2 = (X 0 : R3 k) * ((X 2 : R3 k) * h) := by
      rw [hh] at h1; linear_combination h1
    simpa [d₃_apply, smul_eq_mul] using
      (mul_left_cancel₀ (MvPolynomial.X_ne_zero 0) this).symm

set_option linter.unusedSimpArgs false in
lemma ker_d₁_eq_range_d₂ :
    LinearMap.ker (d₁ k (R3 k)) = LinearMap.range (d₂ k (R3 k)) := by
  refine le_antisymm ?_ range_d₂_le_ker_d₁
  intro f hf
  have hf' : (X 0 : R3 k) * f 0 + (X 1 : R3 k) * f 1 + (X 2 : R3 k) * f 2 = 0 := by
    have := LinearMap.mem_ker.mp hf
    simpa [d₁_apply, smul_eq_mul] using this
  -- `x₂ * f 2 ∈ (x₀, x₁)`, hence `f 2 = a x₀ + b x₁`.
  have hmem2 : (X 2 : R3 k) * f 2 ∈
      Ideal.span ((X (R := k)) '' ({0, 1} : Set (Fin 3)) : Set (R3 k)) := by
    rw [mem_span_X_pair_iff]
    exact ⟨-f 0, -f 1, by linear_combination hf'⟩
  obtain ⟨a, b, hab⟩ :=
    mem_span_X_pair_iff.mp (mem_span_X_of_X_mul_mem _ 2 (by simp) hmem2)
  -- substituting, `x₀ * (f 0 + x₂ a) + x₁ * (f 1 + x₂ b) = 0`
  have hsub : (X 0 : R3 k) * (f 0 + (X 2 : R3 k) * a) +
      (X 1 : R3 k) * (f 1 + (X 2 : R3 k) * b) = 0 := by
    rw [hab] at hf'; linear_combination hf'
  -- so `x₁ * (f 1 + x₂ b) ∈ (x₀)`
  have hmem1 : (X 1 : R3 k) * (f 1 + (X 2 : R3 k) * b) ∈
      Ideal.span ((X (R := k)) '' ({0} : Set (Fin 3)) : Set (R3 k)) := by
    rw [mem_span_X_singleton_iff]
    exact ⟨-(f 0 + (X 2 : R3 k) * a), by linear_combination hsub⟩
  obtain ⟨c, hc⟩ :=
    mem_span_X_singleton_iff.mp (mem_span_X_of_X_mul_mem _ 1 (by simp) hmem1)
  -- and then `f 0 + x₂ a = -x₁ c` after cancelling `x₀`
  have hc0 : (X 0 : R3 k) * (f 0 + (X 2 : R3 k) * a) =
      (X 0 : R3 k) * (-((X 1 : R3 k) * c)) := by
    rw [hc] at hsub; linear_combination hsub
  have hf0 : f 0 + (X 2 : R3 k) * a = -((X 1 : R3 k) * c) :=
    mul_left_cancel₀ (MvPolynomial.X_ne_zero 0) hc0
  refine ⟨![b, -a, c], ?_⟩
  have e0 : d₂ k (R3 k) ![b, -a, c] 0 = f 0 := by
    rw [d₂_apply_zero]
    simp only [Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_two,
      Matrix.head_cons, Matrix.tail_cons, smul_eq_mul]
    linear_combination -hf0
  have e1 : d₂ k (R3 k) ![b, -a, c] 1 = f 1 := by
    rw [d₂_apply_one]
    simp only [Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_two,
      Matrix.head_cons, Matrix.tail_cons, smul_eq_mul]
    linear_combination -hc
  have e2 : d₂ k (R3 k) ![b, -a, c] 2 = f 2 := by
    rw [d₂_apply_two]
    simp only [Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_two,
      Matrix.head_cons, Matrix.tail_cons, smul_eq_mul]
    linear_combination -hab
  funext i
  fin_cases i
  · exact e0
  · exact e1
  · exact e2

end Ring

/-! ## Transfer to finite free modules

Exactness is checked coordinatewise, so it survives passage from `R3 k` to a
free module `ι → R3 k`.  This is the form in which the complex is used: the
Koszul homology of a free module vanishes in positive degrees. -/

section Free

variable {k : Type u} [Field k] {ι : Type w}

lemma d₁_pi_apply (f : Fin 3 → (ι → R3 k)) (c : ι) :
    d₁ k (ι → R3 k) f c = d₁ k (R3 k) (fun i => f i c) := by
  simp only [d₁_apply, Pi.add_apply, Pi.smul_apply, smul_eq_mul]

lemma d₂_pi_apply (g : Fin 3 → (ι → R3 k)) (i : Fin 3) (c : ι) :
    d₂ k (ι → R3 k) g i c = d₂ k (R3 k) (fun j => g j c) i := by
  simp only [d₂_apply, Pi.sub_apply, Pi.smul_apply, smul_eq_mul]

lemma d₃_pi_apply (m : ι → R3 k) (i : Fin 3) (c : ι) :
    d₃ k (ι → R3 k) m i c = d₃ k (R3 k) (m c) i := by
  simp only [d₃_apply, Pi.smul_apply, smul_eq_mul]

lemma d₃_pi_injective : Function.Injective (d₃ k (ι → R3 k)) := by
  intro m m' h
  funext c
  refine d₃_injective (k := k) ?_
  funext i
  rw [← d₃_pi_apply, ← d₃_pi_apply, h]

lemma ker_d₂_eq_range_d₃_pi :
    LinearMap.ker (d₂ k (ι → R3 k)) = LinearMap.range (d₃ k (ι → R3 k)) := by
  refine le_antisymm ?_ range_d₃_le_ker_d₂
  intro g hg
  have hg' := LinearMap.mem_ker.mp hg
  have hker : ∀ c : ι, ∃ h : R3 k, d₃ k (R3 k) h = fun j => g j c := by
    intro c
    have hzero : d₂ k (R3 k) (fun j => g j c) = 0 := by
      funext i
      rw [← d₂_pi_apply]
      simpa using congrFun (congrFun hg' i) c
    have hmem : (fun j => g j c) ∈ LinearMap.range (d₃ k (R3 k)) := by
      rw [← ker_d₂_eq_range_d₃]
      exact LinearMap.mem_ker.mpr hzero
    exact hmem
  choose h hh using hker
  refine ⟨h, ?_⟩
  funext i c
  rw [d₃_pi_apply]
  exact congrFun (hh c) i

lemma ker_d₁_eq_range_d₂_pi :
    LinearMap.ker (d₁ k (ι → R3 k)) = LinearMap.range (d₂ k (ι → R3 k)) := by
  refine le_antisymm ?_ range_d₂_le_ker_d₁
  intro f hf
  have hf' := LinearMap.mem_ker.mp hf
  have hker : ∀ c : ι, ∃ g : Fin 3 → R3 k, d₂ k (R3 k) g = fun i => f i c := by
    intro c
    have hzero : d₁ k (R3 k) (fun i => f i c) = 0 := by
      rw [← d₁_pi_apply]
      exact congrFun hf' c
    have hmem : (fun i => f i c) ∈ LinearMap.range (d₂ k (R3 k)) := by
      rw [← ker_d₁_eq_range_d₂]
      exact LinearMap.mem_ker.mpr hzero
    exact hmem
  choose g hg using hker
  refine ⟨fun i c => g c i, ?_⟩
  funext i c
  rw [d₂_pi_apply]
  exact congrFun (hg c) i

end Free

end Koszul

end LogConcavity

/-! ## Axiom audit -/

#print axioms LogConcavity.Koszul.d₁_comp_d₂
#print axioms LogConcavity.Koszul.d₂_comp_d₃
#print axioms LogConcavity.Koszul.mem_ker_d₃_iff
#print axioms LogConcavity.Koszul.d₃_injective
#print axioms LogConcavity.Koszul.ker_d₂_eq_range_d₃
#print axioms LogConcavity.Koszul.ker_d₁_eq_range_d₂
#print axioms LogConcavity.Koszul.d₃_pi_injective
#print axioms LogConcavity.Koszul.ker_d₂_eq_range_d₃_pi
#print axioms LogConcavity.Koszul.ker_d₁_eq_range_d₂_pi
