import BettiThree
import Witness

/-!
# The statement, in one file

This file is the entry point for a reader who wants to check *what* has been
proved without reading the proofs.  It contains no new mathematics: it
restates the definitions the main theorem depends on, names the hypothesis of
the paper's Lemma 1, and records the endpoint together with its axiom audit
and a concrete instance.

Everything below refers to `paper/type2-log-concavity.pdf`, whose Theorem 1
is the case `(r, t) = (3, 2)` left open in

> F. Zanello, *Log-concavity of level Hilbert functions and pure
> O-sequences*, arXiv:2210.09447.

## The chain to check

A reader auditing this development only has to be convinced of four things.
All four are checkable from this file alone.

1. **The definitions mean what they say.**  `R3`, `quotPiece`, `hilb`,
   `socle`, `IsTypeTwoLevel` and `GorensteinQuotientHF` are reproduced below
   with commentary; each is the definition used verbatim by the endpoint.
2. **The endpoint says what the paper's Theorem 1 says.**  See
   `theorem1_log_concave` and the discussion above it.
3. **The only assumption is the paper's Lemma 1.**  See `StanleyLemma1`.
4. **Nothing is hiding.**  The `#print axioms` block at the bottom reports
   Lean's three standard foundational axioms and nothing else, and
   `theorem1_witness` instantiates the whole thing at an explicit algebra, so
   the hypotheses are not vacuous.

## The definitions, in the order they are used

`R3 k = MvPolynomial (Fin 3) k` is `R = k[x₁, x₂, x₃]` (`LogConcavity.lean`).

```lean
noncomputable def quotPiece (I : Ideal (R3 k)) (n : ℕ) : Submodule k (R3 k ⧸ I) :=
  (homogeneousSubmodule (Fin 3) k n).map (Ideal.Quotient.mkₐ k I).toLinearMap

noncomputable def hilb (I : Ideal (R3 k)) (t : ℤ) : ℤ :=
  if 0 ≤ t then (finrank k (quotPiece I t.toNat) : ℤ) else 0
```

So `quotPiece I n` is the image of `Rₙ` in `A = R/I` — for a homogeneous `I`
this is the degree-`n` graded piece of `A` — and `hilb I` is its `k`-dimension,
extended by zero to negative degrees.  `hilb` is the Hilbert function of the
statement; nothing else in this development is called one.

```lean
def socle (I : Ideal (R3 k)) : Submodule k (R3 k ⧸ I) where
  carrier := {a | ∀ j : Fin 3, Ideal.Quotient.mk I (X j) * a = 0}
```

The irrelevant maximal ideal is generated by the three variables, so this is
`(0 :_A m)`, the socle of `A`.

```lean
structure IsTypeTwoLevel (I : Ideal (R3 k)) (e : ℕ) : Prop where
  homogeneous     : I.IsHomogeneous (homogeneousSubmodule (Fin 3) k)
  proper          : I ≠ ⊤
  no_linear_forms : ∀ f ∈ I, MvPolynomial.IsHomogeneous f 1 → f = 0
  finiteDimensional : FiniteDimensional k (R3 k ⧸ I)
  vanish_above    : ∀ n : ℕ, e < n → quotPiece I n = ⊥
  socle_concentrated : socle I ≤ quotPiece I e
  type_two        : finrank k (socle I) = 2
```

Field by field: `A = R/I` is standard graded (`homogeneous`, `proper`), has
embedding dimension exactly three (`no_linear_forms` — `I` contains no linear
form), is Artinian (`finiteDimensional`), has socle degree `e` and is level
(`vanish_above` + `socle_concentrated`; `IsTypeTwoLevel.socle_eq` upgrades the
containment to `socle I = quotPiece I e`), and has type two (`type_two`).
That is exactly the hypothesis of the paper's Theorem 1.

The profile asserted in the paper's `h = (1, 3, h₂, …, h_e = 2)` is *derived*
from these fields rather than assumed — see `hilb_zero`,
`IsTypeTwoLevel.hilb_one`, `IsTypeTwoLevel.hilb_top`,
`IsTypeTwoLevel.hilb_vanish` and `IsTypeTwoLevel.two_le_socleDegree` — which
is the main sanity check that the structure is not accidentally stronger or
weaker than intended.

```lean
def GorensteinQuotientHF (B : ℤ → ℤ) (E : ℤ) : Prop :=
  ∃ (J : Ideal (R3 k)) (E' : ℕ), (E' : ℤ) = E ∧
    J.IsHomogeneous (homogeneousSubmodule (Fin 3) k) ∧ J ≠ ⊤ ∧
    FiniteDimensional k (R3 k ⧸ J) ∧
    (∀ n : ℕ, E' < n → quotPiece J n = ⊥) ∧
    socle J ≤ quotPiece J E' ∧ finrank k (socle J) = 1 ∧
    ∀ t : ℤ, B t = hilb J t
```

`B` is the Hilbert function of a standard graded Artinian quotient of
`k[x₁, x₂, x₃]` — hence of embedding dimension at most three — whose socle is
one-dimensional and concentrated in degree `E`.  That is "`B` is the Hilbert
function of an Artinian Gorenstein algebra of embedding dimension at most
three and socle degree `E`", the hypothesis of the paper's Lemma 1.  Note
that `B` is pinned to `hilb J` at *every* degree, so this predicate cannot be
satisfied by an unrelated function.
-/

namespace LogConcavity

universe u
variable {k : Type u} [Field k]

/-! ## The assumption: Lemma 1 of the paper -/

/-- **Lemma 1 (Stanley), as assumed.**  The Hilbert function of a standard
graded Artinian Gorenstein algebra of embedding dimension at most three and
socle degree `E` is nondecreasing through degree `⌊E/2⌋`.  For integers,
`i ≤ ⌊E/2⌋` is `2 * i ≤ E`.

This is the *only* mathematical input the development does not prove.  It is
a published theorem:

* R. P. Stanley, *Hilbert functions of graded algebras*, Adv. Math. 28
  (1978), 57–83 (the codimension-three Gorenstein case, via the
  Buchsbaum–Eisenbud structure theorem);
* F. Zanello, *Stanley's theorem on codimension 3 Gorenstein h-vectors*,
  Proc. Amer. Math. Soc. 134 (2006), 5–8, arXiv:math/0411231 — the
  characteristic-free proof cited by the paper.

Two remarks on the exact form assumed here.

*Only monotonicity.*  Stanley's theorem says the Hilbert function is an
SI-sequence: symmetric, with the first difference of its first half an
O-sequence.  Only the monotonicity through `⌊E/2⌋` is assumed, which is the
weakest consequence the proof uses (the paper says as much after Lemma 1).

*All fields, including finite ones.*  This is quantified over the given field
`k` with no infiniteness hypothesis, matching the paper's "the result holds
over an arbitrary field".  Arguments via a general linear form are usually
written over an infinite field; the reduction is standard and lossless, since
for a field extension `k ⊆ k'` the algebra `A ⊗_k k'` has the same Hilbert
function as `A` and the same socle dimension (base change along a field
extension is exact, and the socle is the kernel of a `k`-linear map), so
Gorenstein-ness, the socle degree and the Hilbert function are all preserved
on passing to an infinite extension. -/
def StanleyLemma1 (k : Type u) [Field k] : Prop :=
  ∀ B E, GorensteinQuotientHF k B E →
    ∀ i j : ℤ, 0 ≤ j → j ≤ i → 2 * i ≤ E → B j ≤ B i

/-! ## The theorem -/

/-- **Theorem 1 of the paper.**  Let `A = R/I` with `R = k[x₁, x₂, x₃]` and
`k` any field, and suppose `A` is a standard graded Artinian level algebra of
embedding dimension three, socle degree `e` and type two.  Then its Hilbert
function is log-concave:

`hᵢ₋₁ · hᵢ₊₁ ≤ hᵢ²` for `1 ≤ i ≤ e − 1`.

The single hypothesis beyond the algebra itself is `StanleyLemma1 k`.  In
particular there is no hypothesis on the characteristic of `k` and none on
its cardinality, and no numerical data about a resolution is assumed: the
minimal graded free complex of the Matlis dual, its shifts, the rank-one last
syzygy of the paper's display (1), and the Gorenstein algebra `B` of the
critical branch are all constructed from `hA`. -/
theorem theorem1_log_concave
    (e : ℕ) (I : Ideal (R3 k)) (hA : IsTypeTwoLevel I e)
    (hStanley : StanleyLemma1 k) :
    ∀ i : ℤ, 1 ≤ i → i ≤ (e : ℤ) - 1 →
      hilb I (i - 1) * hilb I (i + 1) ≤ hilb I i ^ 2 :=
  theorem1_modulo_Stanley e I hA hStanley

/-! ## The hypotheses are not vacuous

`IsTypeTwoLevel` is satisfiable: `Witness.lean` constructs
`J = (xy, xz, y², z², x³) ⊆ k[x, y, z]` — the inverse system `⟨X², YZ⟩` — and
checks every field of the structure from the monomial generators, including
`finrank (socle J) = 2` from an explicit basis `{x², yz}`.  Feeding it through
the development's own derivations pins its Hilbert function to `(1, 3, 2)`.

Below, the endpoint itself is run on that algebra.  Since `e = 2` the tested
range `1 ≤ i ≤ e − 1` is the single index `i = 1`, and the conclusion is the
concrete inequality `h₀ · h₂ = 2 ≤ 9 = h₁²`. -/
theorem theorem1_witness (hStanley : StanleyLemma1 k) :
    hilb (witnessIdeal k) 0 * hilb (witnessIdeal k) 2
      ≤ hilb (witnessIdeal k) 1 ^ 2 := by
  have h := theorem1_log_concave 2 (witnessIdeal k) isTypeTwoLevel_witness hStanley 1
    (by norm_num) (by norm_num)
  norm_num at h
  exact h

/-- The same inequality with both sides evaluated, from the witness Hilbert
function `(1, 3, 2)` — no hypotheses at all. -/
example : hilb (witnessIdeal k) 0 * hilb (witnessIdeal k) 2
    ≤ hilb (witnessIdeal k) 1 ^ 2 := witness_log_concave

end LogConcavity

/-! ## Axiom audit

Every declaration named here must depend on `propext`, `Classical.choice` and
`Quot.sound` only.  Anything else — in particular `sorryAx` — would appear in
these lines, and CI fails the build if it does. -/

#print axioms LogConcavity.theorem1_log_concave
#print axioms LogConcavity.theorem1_witness
#print axioms LogConcavity.theorem1_modulo_Stanley
#print axioms LogConcavity.isTypeTwoLevel_witness
